import { StyleSheet} from 'react-native';
const POINTER_SIZE = 10;
const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'white' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    backgroundColor: '#fff',
  },
  headerTitle: { fontSize: 22, fontWeight: '600' },
  card1: {
    marginTop: 8,
    borderWidth: 0.2,
    borderColor: 'gray',
    marginHorizontal: 10,
    borderRadius: 2,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 1,
    margin: 16,
    padding: 1,
  },
  stockOverview: { flexDirection: 'row', alignItems: 'center' },
  logoCircle: {
    borderRadius: 32,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: { width: 40, height: 40 },
  logoPlaceholder: { width: 40, height: 40 },
  stockText: { marginLeft: 12, flex: 1 },
  companyName: { fontSize: 14, fontWeight: '600' },
  symbolText: { fontSize: 10, color: '#666' },
  exchangeText: { fontSize: 9, color: '#999' },
  priceBlock: { alignItems: 'flex-end' },
  price: { fontSize: 14, fontWeight: '700' },
  changePct: { fontSize: 12, marginTop: 4 },
  pos: { color: '#16c784' },
  neg: { color: '#ea3943' },

  chartCard: {
    backgroundColor: '#fff',
    borderRadius: 2,
    marginHorizontal: 10,
    padding: 10,
    borderWidth: 0.2,
    borderColor: 'gray',
    alignItems: 'center',
  },
  rangeButtons: {
    width: 180,
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: 50,
    borderWidth: 1,
    maxWidth: 400,
    borderColor: '#ccc',
    paddingVertical: 6,
    marginBottom: 5,
  },
  rangeBtn: {
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 100,
  },
  rangeText: { fontSize: 12 },
  rangeActive: {
    backgroundColor: '#0a84ff',
    borderColor: '#0a84ff',
    borderRadius: 100,
  },
  rangeActiveText: { color: '#fff' },

  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomColor: 'gray',
    borderBottomWidth: 0.3,
  },
  description: { fontSize: 14, color: '#444', lineHeight: 20 },
  tagsRow: { flexDirection: 'row', marginTop: 12, flexWrap: 'wrap' },
  tag: {
    backgroundColor: '#B4C1FF',
    borderRadius: 30,
    borderWidth: 0.4,
    borderColor: '#0048FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 4,
    marginBottom: 5,
  },
  tagText: { fontSize: 12, color: 'black' },

  /* ─── Slider Styles ─── */
  sliderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 1,
    marginBottom: 4,
  },
  sliderHeaderText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
  },
  sliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 8,
  },
  sliderLabel: {
    width: 50,
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
  },
  sliderBar: {
    flex: 1,
    height: 2,
    backgroundColor: '#ccc',
    marginHorizontal: 8,
    position: 'relative',
  },
  sliderPointer: {
    width: POINTER_SIZE,
    height: POINTER_SIZE,
    borderRadius: POINTER_SIZE / 2,
    backgroundColor: '#0a84ff',
    position: 'absolute',
    top: -((POINTER_SIZE / 2) - 1),
  },
  currentPriceLabel: {
    textAlign: 'center',
    fontSize: 12,
    color: '#444',
    marginBottom: 12,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingHorizontal: 2,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 12,
    color: '#888',
  },
  statValue: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
});

export default s